[project]
name = "eman-ege-check-progress"
version = "0.2.0"
description = "EMAN-EGE Check Progress"
requires-python = ">=3.12,<3.14"
dependencies = [
    "flet==0.86.5",
    "flet-charts==0.86.5",
]

[tool.flet]
product = "EMAN-EGE Check Progress"

[tool.flet.web]
route_url_strategy = "hash"
pwa_background_color = "#050A0F"
pwa_theme_color = "#16D8FF"

[tool.flet.splash]
color = "#050A0F"
dark_color = "#050A0F"

[tool.flet.boot_screen.flet]
theme_mode = "dark"
bgcolor_dark = "#050A0F"
spinner_color_dark = "#16D8FF"
spinner_size = 28
text_color_dark = "#E4EDF2"
